### ISSUE TITLE
Case insensitive autocomplete does not work for some commands (zsh)

### ISSUE THREAD

**Issue by lcroberts** [sigoden/argc-completions#16]
I'm using zsh with cases insensitive completion. When using 7zip I noticed that when providing a the directory to add to an archive completion is case sensitive. 
Example: `7z a test.7z ...` When using argc-completions completions for files/directories where `...` is will be case sensitive, however without it completion options are case insensitive as expected.

**Comment by sigoden** [comment]
Case sensitive make sence, because file system is case  sensitive.
![image](https://github.com/sigoden/argc-completions/assets/4012553/695f22d5-15ee-4253-8e56-ce007a3db647)

Someone use case insensitive for convenience，someone don't use. 

argc-completions currently defaults to being case sensitive.
